# Nonzero locations in Sparse matrices!

We can locate/find the nonzero entries in a sparse matrix in at least two ways.  

In [10]:
using MatrixMarket, SparseArrays
cd("C:\\Users\\AllanStruthers\\Desktop\\GitHub\\23-24-Classes\\Spring 2024 Courses\\Lin Alg\\Projects\\ILU0")
A=mmread("ILU0Test.mtx")

59×59 SparseMatrixCSC{Float64, Int64} with 313 stored entries:
⎡⠑⢄⠈⠢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠑⢄⠈⠢⡀⠐⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠑⣤⠬⠆⠀⠑⣀⣀⡀⠀⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠈⠳⣄⠀⠀⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⣿⣿⡏⠢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣍⠁⠀⠈⠐⢄⠀⠢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⠀⠈⠓⢄⠀⠀⠀⠑⠀⠈⢢⠤⠤⠄⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠀⠀⠀⠀⠀⠑⢄⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⢡⣤⣤⠰⠒⠒⡄⠀⠀⠀⎥
⎢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⠀⠑⠄⡇⠀⠀⠀⎥
⎢⠈⠢⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⢄⠀⠀⡇⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠤⠤⠘⢍⠉⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠁⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡀⠀⠀⠀⠑⠀⠀⠀⠀⠀⠀⠀⠀⠱⣄⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⠄⎦

In [37]:
B=copy(A[11:16,11:15])

6×5 SparseMatrixCSC{Float64, Int64} with 14 stored entries:
 7.2  -1.0  -1.0  -1.0  -1.0
 1.0   8.2    ⋅     ⋅     ⋅ 
  ⋅    1.0   8.2    ⋅     ⋅ 
  ⋅     ⋅    1.0   8.2    ⋅ 
  ⋅     ⋅     ⋅    1.0   8.2
  ⋅     ⋅     ⋅     ⋅    1.0

"findnz" gives you a tuple containing the $i_k$, $j_k$, and $B_{i_k,j_k}$ for k in 1:nnz(B).  The order of the entries is down the first column, then down the second column, then down the third column etc.  This is because the B matrix is in compressed column CSC format. 

In [38]:
(m, n) = size(B)
DenseB1 = zeros(m,n);
(is, js, bs) = findnz(B)
for k in 1:nnz(B)
    DenseB1[is[k],js[k]]=bs[k]
end
DenseB1

6×5 Matrix{Float64}:
 7.2  -1.0  -1.0  -1.0  -1.0
 1.0   8.2   0.0   0.0   0.0
 0.0   1.0   8.2   0.0   0.0
 0.0   0.0   1.0   8.2   0.0
 0.0   0.0   0.0   1.0   8.2
 0.0   0.0   0.0   0.0   1.0

You can reconstruct a dense matrix directly out of the fields of a sparse matrix B.  The fields are: dimensions B.m and B.n; vector of values B.nzval stored in the column order described above; vector of column pointers B.colptr which locate the nonzero values in the B.nzval; and vector of row indices B.rowval. 

So you can display the nonzero entries in each column as follows.

In [47]:
(m, n) = size(B)
# Extracting fields from sparse matrix B
vals = B.nzval
cols = B.colptr
for j in 1:B.n
    display(vals[cols[j]:cols[j+1]-1])
end

2-element Vector{Float64}:
 7.2
 1.0

3-element Vector{Float64}:
 -1.0
  8.2
  1.0

3-element Vector{Float64}:
 -1.0
  8.2
  1.0

3-element Vector{Float64}:
 -1.0
  8.2
  1.0

3-element Vector{Float64}:
 -1.0
  8.2
  1.0

Incorporating the rowval field lets you reconstruct the dense matrix.  

In [64]:
(m, n) = size(B)
DenseB2 = zeros(m,n);
vals = B.nzval
cols = B.colptr
rows = B.rowval 
for j in 1:B.n
    for k in cols[j]:cols[j+1]-1
        i = rows[k]
        b = vals[k]
        DenseB2[i,j] = b
    end
end
DenseB2

6×5 Matrix{Float64}:
 7.2  -1.0  -1.0  -1.0  -1.0
 1.0   8.2   0.0   0.0   0.0
 0.0   1.0   8.2   0.0   0.0
 0.0   0.0   1.0   8.2   0.0
 0.0   0.0   0.0   1.0   8.2
 0.0   0.0   0.0   0.0   1.0

In [60]:
cols

6-element Vector{Int64}:
  1
  3
  6
  9
 12
 15

In [59]:
DenseB2

6×5 Matrix{Float64}:
  1.0   0.0   0.0  0.0  0.0
 -1.0   0.0   0.0  0.0  0.0
  0.0  -1.0   0.0  0.0  0.0
  0.0   8.2   0.0  0.0  0.0
  0.0   1.0   0.0  0.0  0.0
  0.0   0.0  -1.0  0.0  0.0