# Householder and Givens Tools

The plan is to implement a number of things in pure Julia to provide access to the AD tools.

1. Single step in place two-sided Householder reduction
1. XXX

In [104]:
using Pkg
# Pkg.add("Gadfly")
using LinearAlgebra, Gadfly
m=4;
A = rand(m,m); H=copy(A)
v=zeros(m)
v[2:m] = H[2:m,1];
v[2]+=norm(v);
v = v/norm(v);
H = H - 2.0*(H*v)*v';
H = H - 2.0*v*(H'*v)';
norm(eigen(A).values-eigen(H).values)
H

4×4 Matrix{Float64}:
  0.259098     -0.865233   -0.537316   0.00115405
 -1.43298       1.74446    -0.185918   0.259714
  0.0           0.0797151   0.250835   0.198617
 -1.11022e-16   0.131313   -0.102626  -0.228004

In [54]:
eigen(A).values

4-element Vector{ComplexF64}:
 -0.2699678680770858 - 0.23689486356907233im
 -0.2699678680770858 + 0.23689486356907233im
  0.5259899376667638 + 0.0im
  1.8432171191001872 + 0.0im

In [32]:
u=rand(m);
UU=u*u'
norm(H*UU-(H*u)*u')
norm(UU*H - u*(H'*u)' )

4.619472857234462e-16

Eigenvectors in the eigen command are in the columns of the output.

In [34]:
using LinearAlgebra
(lambda, V)=eigen(A)

norm(A*V[:,1] -lambda[1]*V[:,1])

2.277987190955421e-15

You can call out individual entries of a matrix or vector using indices and 

In [35]:
A

3×3 Matrix{Float64}:
 -0.566934   1.68297    1.33585
  1.28433   -0.475388   1.14267
 -0.586654   0.633992  -0.382523

In [38]:
(i,j)=(2,3)
A[i,j]

1.142665811032841